#  Copyright (c) 2024-2025 ETH Zurich
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  This open source software code was developed in part or in whole in the
#  Human Brain Project, funded from the European Union's Horizon 2020
#  Framework Programme for Research and Innovation under
#  Specific Grant Agreements No. 720270, No. 785907, and No. 945539
#  (Human Brain Project SGA1, SGA2 and SGA3).
#
import copy
import time
from concurrent.futures import wait
from concurrent.futures.thread import ThreadPoolExecutor
from typing import Dict, Any, Self, List, Optional
from uuid import UUID

import math
import requests
from requests import Response

from ._client import Translator, AbstractClientBuilder, fetch_by_open_id_config, Config, OIDCConfig
from ._communication import Communication, create_endpoint
from .models import (JsonLdDocument, Instance, Scope, SpaceInformation, TypeInformation,
                     User, UserWithRoles, ReleaseStatus, ListOfUUID, Stage, ReleaseTreeScope)
from .result import (EmptyResult, Result, translate_empty_result, translate_result, ResultsById,
                     ResultPage, translate_results_by_id, translate_result_page, ResultPageBuilderContext)


class MarmotGraph(object):
    """
    The Python SDK for the API version  of MarmotGraph

    ATTENTION! This class is autogenerated! Do not apply any manual changes!
    """


    class Client(object):

        def __init__(self, config: Config):
            self.id_namespace = config.id_namespace if config else None
            self.admin = MarmotGraph.Admin(config)
            self.instances = MarmotGraph.Instances(config)
            self.jsonld = MarmotGraph.Jsonld(config)
            self.queries = MarmotGraph.Queries(config)
            self.setup = MarmotGraph.Setup(config)
            self.spaces = MarmotGraph.Spaces(config)
            self.types = MarmotGraph.Types(config)
            self.users = MarmotGraph.Users(config)
            
        def uuid_from_instance_id(self, instance_id: str) -> UUID:
            return Translator.from_instance_id(instance_id, self.id_namespace)

        def instance_id_from_uuid(self, uuid: UUID) -> str:
            return Translator.to_instance_id(uuid, self.id_namespace)
    
    class Admin(Communication):
        def __init__(self, config: Config):
            super().__init__(config)
    
        class AssignTypeToSpaceBuilder(object):

            def __init__(self, parent: Communication, space: str, target_type: str):
                self._parent = parent
                
                self.space: str = space
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "type": target_type
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/spaces/{space}/types"
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_empty_result(result)
            
        def assign_type_to_space(self, space: str, target_type: str) -> AssignTypeToSpaceBuilder:
            """
            Assign a type to a space
            """
            return self.AssignTypeToSpaceBuilder(self, space, target_type)
        
        class CalculateInstanceInvitationScopeBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/instances/{id}/invitationScope"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_empty_result(result)
            
        def calculate_instance_invitation_scope(self, instance_id: UUID) -> CalculateInstanceInvitationScopeBuilder:
            """
            Update invitation scope for this instance
            """
            return self.CalculateInstanceInvitationScopeBuilder(self, instance_id)
        
        class CreateSpaceDefinitionBuilder(object):

            def __init__(self, parent: Communication, space: str):
                self._parent = parent
                
                self.space: str = space
                self.params: Dict[str, Any] = {
                    "autorelease": False, 
                    "clientSpace": False, 
                    "deferCache": False, 
                    "scopeRelevant": False
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/spaces/{space}/specification"
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_empty_result(result)
            
            def autorelease(self) -> Self:
                self.params["autorelease"] = True
                return self
            
            def client_space(self) -> Self:
                self.params["clientSpace"] = True
                return self
            
            def defer_cache(self) -> Self:
                self.params["deferCache"] = True
                return self
            
            def scope_relevant(self) -> Self:
                self.params["scopeRelevant"] = True
                return self
            
        def create_space_definition(self, space: str) -> CreateSpaceDefinitionBuilder:
            """
            Explicitly specify a space
            """
            return self.CreateSpaceDefinitionBuilder(self, space)
        
        class CreateTypeDefinitionBuilder(object):

            def __init__(self, parent: Communication, target_type: str):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "type": target_type
                })
            
            def invoke(self, payload: JsonLdDocument) -> EmptyResult:
                path: str = "/v3/types/specification"
                invocation_params = self.params
                result: Response = self._parent.put_request(path, payload, invocation_params)
                return translate_empty_result(result)
            
            def is_global(self, is_global: bool) -> Self:
                self.params["global"] = is_global
                return self
            
        def create_type_definition(self, target_type: str) -> CreateTypeDefinitionBuilder:
            """
            Specify a type
            """
            return self.CreateTypeDefinitionBuilder(self, target_type)
        
        class DefinePropertyBuilder(object):

            def __init__(self, parent: Communication, property_name: str):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "property": property_name
                })
            
            def invoke(self, payload: JsonLdDocument) -> EmptyResult:
                path: str = "/v3/properties"
                invocation_params = self.params
                result: Response = self._parent.put_request(path, payload, invocation_params)
                return translate_empty_result(result)
            
            def is_global(self, is_global: bool) -> Self:
                self.params["global"] = is_global
                return self
            
        def define_property(self, property_name: str) -> DefinePropertyBuilder:
            """
            Upload a property specification either globally or for the requesting client
            """
            return self.DefinePropertyBuilder(self, property_name)
        
        class DefinePropertyForTypeBuilder(object):

            def __init__(self, parent: Communication, property_name: str, target_type: str):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "property": property_name, 
                    "type": target_type
                })
            
            def invoke(self, payload: JsonLdDocument) -> EmptyResult:
                path: str = "/v3/propertiesForType"
                invocation_params = self.params
                result: Response = self._parent.put_request(path, payload, invocation_params)
                return translate_empty_result(result)
            
            def is_global(self, is_global: bool) -> Self:
                self.params["global"] = is_global
                return self
            
        def define_property_for_type(self, property_name: str, target_type: str) -> DefinePropertyForTypeBuilder:
            """
            Define a property specification either globally for the requesting client
            """
            return self.DefinePropertyForTypeBuilder(self, property_name, target_type)
        
        class DeprecatePropertyBuilder(object):

            def __init__(self, parent: Communication, property_name: str):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "property": property_name
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/properties"
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
            def is_global(self, is_global: bool) -> Self:
                self.params["global"] = is_global
                return self
            
        def deprecate_property(self, property_name: str) -> DeprecatePropertyBuilder:
            """
            Upload a property specification either globally or for the requesting client
            """
            return self.DeprecatePropertyBuilder(self, property_name)
        
        class DeprecatePropertyForTypeBuilder(object):

            def __init__(self, parent: Communication, property_name: str, target_type: str):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "property": property_name, 
                    "type": target_type
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/propertiesForType"
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
            def is_global(self, is_global: bool) -> Self:
                self.params["global"] = is_global
                return self
            
        def deprecate_property_for_type(self, property_name: str, target_type: str) -> DeprecatePropertyForTypeBuilder:
            """
            Deprecate a property specification for a specific type either globally or for the requesting client
            """
            return self.DeprecatePropertyForTypeBuilder(self, property_name, target_type)
        
        class GetAllRoleDefinitionsBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/setup/permissions"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_empty_result(result)
            
        def get_all_role_definitions(self, ) -> GetAllRoleDefinitionsBuilder:
            
            return self.GetAllRoleDefinitionsBuilder(self)
        
        class GetAvailableChecksBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/health"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_empty_result(result)
            
        def get_available_checks(self, ) -> GetAvailableChecksBuilder:
            
            return self.GetAvailableChecksBuilder(self)
        
        class GetClaimForRoleBuilder(object):

            def __init__(self, parent: Communication, role: str):
                self._parent = parent
                
                self.role: str = role
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/setup/permissions/{role}"
                path = path.replace("{role}", str(self.role))
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_empty_result(result)
            
            def space(self, space: str) -> Self:
                self.params["space"] = space
                return self
            
        def get_claim_for_role(self, role: str) -> GetClaimForRoleBuilder:
            
            return self.GetClaimForRoleBuilder(self, role)
        
        class GetReportBuilder(object):

            def __init__(self, parent: Communication, name: str):
                self._parent = parent
                
                self.name: str = name
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> EmptyResult:
                path: str = "/v3/health/{name}"
                path = path.replace("{name}", str(self.name))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_empty_result(result)
            
        def get_report(self, name: str) -> GetReportBuilder:
            
            return self.GetReportBuilder(self, name)
        
        class HealthStatusBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/health"
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_empty_result(result)
            
        def health_status(self, ) -> HealthStatusBuilder:
            
            return self.HealthStatusBuilder(self)
        
        class RemoveSpaceDefinitionBuilder(object):

            def __init__(self, parent: Communication, space: str):
                self._parent = parent
                
                self.space: str = space
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/spaces/{space}/specification"
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
        def remove_space_definition(self, space: str) -> RemoveSpaceDefinitionBuilder:
            """
            Remove a space definition
            """
            return self.RemoveSpaceDefinitionBuilder(self, space)
        
        class RemoveTypeDefinitionBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/types/specification"
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
            def is_global(self, is_global: bool) -> Self:
                self.params["global"] = is_global
                return self
            
            def target_type(self, target_type: str) -> Self:
                self.params["type"] = target_type
                return self
            
        def remove_type_definition(self, ) -> RemoveTypeDefinitionBuilder:
            """
            Remove a type definition
            """
            return self.RemoveTypeDefinitionBuilder(self)
        
        class RemoveTypeFromSpaceBuilder(object):

            def __init__(self, parent: Communication, space: str, target_type: str):
                self._parent = parent
                
                self.space: str = space
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "type": target_type
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/spaces/{space}/types"
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
        def remove_type_from_space(self, space: str, target_type: str) -> RemoveTypeFromSpaceBuilder:
            """
            Remove a type in space definition
            """
            return self.RemoveTypeFromSpaceBuilder(self, space, target_type)
        
        class RerunEventsBuilder(object):

            def __init__(self, parent: Communication, space: str):
                self._parent = parent
                
                self.space: str = space
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/spaces/{space}/eventHistory"
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_empty_result(result)
            
        def rerun_events(self, space: str) -> RerunEventsBuilder:
            """
            Trigger a rerun of the events of this space
            """
            return self.RerunEventsBuilder(self, space)
        
        class TriggerInferenceBuilder(object):

            def __init__(self, parent: Communication, space: str):
                self._parent = parent
                
                self.space: str = space
                self.params: Dict[str, Any] = {
                    "async": False
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/spaces/{space}/inference"
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.post_request(path, None, invocation_params)
                return translate_empty_result(result)
            
            def identifier(self, identifier: str) -> Self:
                self.params["identifier"] = identifier
                return self
            
            def is_async(self) -> Self:
                self.params["async"] = True
                return self
            
        def trigger_inference(self, space: str) -> TriggerInferenceBuilder:
            """
            Triggers the inference of all documents of the given space
            """
            return self.TriggerInferenceBuilder(self, space)
        
        class UpdateClaimForRoleBuilder(object):

            def __init__(self, parent: Communication, remove: bool, role: str):
                self._parent = parent
                
                self.role: str = role
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "remove": remove
                })
            
            def invoke(self, payload: Dict[str, Any]) -> EmptyResult:
                path: str = "/v3/setup/permissions/{role}"
                path = path.replace("{role}", str(self.role))
                invocation_params = self.params
                result: Response = self._parent.patch_request(path, payload, invocation_params)
                return translate_empty_result(result)
            
            def space(self, space: str) -> Self:
                self.params["space"] = space
                return self
            
        def update_claim_for_role(self, remove: bool, role: str) -> UpdateClaimForRoleBuilder:
            
            return self.UpdateClaimForRoleBuilder(self, remove, role)
        
    class Instances(Communication):
        def __init__(self, config: Config):
            super().__init__(config)


        class ContributeToInstanceFullReplacementBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self, payload: JsonLdDocument) -> Result[Instance]:
                path: str = "/v3/instances/{id}"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, payload, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self

            def skip_if_unchanged(self) -> Self:
                self.params["skipIfUnchanged"] = True
                return self
            
        def contribute_to_full_replacement(self, instance_id: UUID) -> ContributeToInstanceFullReplacementBuilder:
            """
            Replace contribution to an existing instance
            """
            return self.ContributeToInstanceFullReplacementBuilder(self, instance_id)
        
        class ContributeToInstancePartialReplacementBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self, payload: JsonLdDocument) -> Result[Instance]:
                path: str = "/v3/instances/{id}"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.patch_request(path, payload, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self

            def skip_if_unchanged(self) -> Self:
                self.params["skipIfUnchanged"] = True
                return self
            
        def contribute_to_partial_replacement(self, instance_id: UUID) -> ContributeToInstancePartialReplacementBuilder:
            """
            Partially update contribution to an existing instance
            """
            return self.ContributeToInstancePartialReplacementBuilder(self, instance_id)
        
        class CreateNewInstanceBuilder(object):

            def __init__(self, parent: Communication, space: str):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "space": space
                })
            
            def invoke(self, payload: JsonLdDocument) -> Result[Instance]:
                path: str = "/v3/instances"
                invocation_params = self.params
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self

            def skip_if_unchanged(self) -> Self:
                self.params["skipIfUnchanged"] = True
                return self

            def update_if_exists(self) -> Self:
                self.params["updateIfExists"] = True
                return self
            
        def create_new(self, space: str) -> CreateNewInstanceBuilder:
            """
            Create new instance with a system generated id
            """
            return self.CreateNewInstanceBuilder(self, space)
        
        class CreateNewInstanceWithIdBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID, space: str):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "space": space
                })
            
            def invoke(self, payload: JsonLdDocument) -> Result[Instance]:
                path: str = "/v3/instances/{id}"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self

            def skip_if_unchanged(self) -> Self:
                self.params["skipIfUnchanged"] = True
                return self

            def update_if_exists(self) -> Self:
                self.params["updateIfExists"] = True
                return self
            
        def create_new_with_id(self, instance_id: UUID, space: str) -> CreateNewInstanceWithIdBuilder:
            """
            Create new instance with a client defined id
            """
            return self.CreateNewInstanceWithIdBuilder(self, instance_id, space)

        class BulkUpdate(object):

            def __init__(self):
                self._operations: Dict[any, JsonLdDocument] = {}


            def add(self, builder: any, payload: JsonLdDocument):
                self._operations[builder] = payload


            def invoke(self, max_workers=5) -> Dict[any, Result[Instance]]:
                if self._operations:
                    futures = {}
                    start_time = time.time_ns()
                    with ThreadPoolExecutor(max_workers=max_workers) as executor:
                        for b, p in self._operations.items():
                            futures[b] = executor.submit(b.invoke, p)
                    # wait all
                    wait(futures.values(), return_when="ALL_COMPLETED")
                    end_time = time.time_ns()
                    duration = math.ceil((end_time - start_time) / 1_000_000)
                    print(f"Handled {len(futures)} instances in {duration} ms - {duration / len(futures)} in average")
                    return {k: v.result() for k, v in futures.items()}
                return {}


        class DeleteInstanceBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/instances/{id}"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
        def delete(self, instance_id: UUID) -> DeleteInstanceBuilder:
            """
            Delete an instance
            """
            return self.DeleteInstanceBuilder(self, instance_id)
        
        class GetInstanceByIdBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[Instance]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> Result[Instance]:
                path: str = "/v3/instances/{id}"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self
            
        def get_by_id(self, instance_id: UUID) -> GetInstanceByIdBuilder:
            """
            Get the instance
            """
            return self.GetInstanceByIdBuilder(self, instance_id)
        
        class GetInstancesByIdentifiersBuilder(object):

            def __init__(self, parent: Communication, ):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self, payload: List[str]) -> ResultsById[Instance]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(payload, self._parent.config.default_stage)

            def invoke_in_stage(self, payload: List[str], stage: Stage) -> ResultsById[Instance]:
                path: str = "/v3/instancesByIdentifiers"
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_results_by_id(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self
            
        def get_by_identifiers(self, ) -> GetInstancesByIdentifiersBuilder:
            """
            Read instances by the given list of (external) identifiers
            """
            return self.GetInstancesByIdentifiersBuilder(self)
        
        class GetInstancesByIdsBuilder(object):

            def __init__(self, parent: Communication, ):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self, payload: List[str]) -> ResultsById[Instance]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(payload, self._parent.config.default_stage)

            def invoke_in_stage(self, payload: List[str], stage: Stage) -> ResultsById[Instance]:
                path: str = "/v3/instancesByIds"
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_results_by_id(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self
            
        def get_by_ids(self, ) -> GetInstancesByIdsBuilder:
            """
            Bulk operation of /instances/{id} to read instances by their UUIDs
            """
            return self.GetInstancesByIdsBuilder(self)
        
        class GetIncomingLinksBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID, property_name: str, target_type: str):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                    "property": property_name, 
                    "type": target_type
                })
            
            def invoke(self) -> ResultPage[Instance]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> ResultPage[Instance]:
                path: str = "/v3/instances/{id}/incomingLinks"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result_page(ResultPageBuilderContext(self, self.invoke_in_stage, stage=stage), self._parent.config.id_namespace, result, Instance)
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
        def get_incoming_links(self, instance_id: UUID, property_name: str, target_type: str) -> GetIncomingLinksBuilder:
            """
            Get incoming links for a specific instance (paginated)
            """
            return self.GetIncomingLinksBuilder(self, instance_id, property_name, target_type)
        
        class GetNeighborsBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> EmptyResult:
                path: str = "/v3/instances/{id}/neighbors"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_empty_result(result)
            
        def get_neighbors(self, instance_id: UUID) -> GetNeighborsBuilder:
            """
            Get the neighborhood for the instance by its KG-internal ID
            """
            return self.GetNeighborsBuilder(self, instance_id)
        
        class GetReleaseStatusBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID, release_tree_scope: ReleaseTreeScope):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "releaseTreeScope": release_tree_scope
                })
            
            def invoke(self) -> Result[ReleaseStatus]:
                path: str = "/v3/instances/{id}/release/status"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, ReleaseStatus)
            
        def get_release_status(self, instance_id: UUID, release_tree_scope: ReleaseTreeScope) -> GetReleaseStatusBuilder:
            """
            Get the release status for an instance
            """
            return self.GetReleaseStatusBuilder(self, instance_id, release_tree_scope)
        
        class GetReleaseStatusByIdsBuilder(object):

            def __init__(self, parent: Communication, release_tree_scope: ReleaseTreeScope):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                    "releaseTreeScope": release_tree_scope
                })
            
            def invoke(self, payload: List[UUID]) -> ResultsById[ReleaseStatus]:
                path: str = "/v3/instancesByIds/release/status"
                invocation_params = self.params
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_results_by_id(self._parent.config.id_namespace, result, ReleaseStatus)
            
        def get_release_status_by_ids(self, release_tree_scope: ReleaseTreeScope) -> GetReleaseStatusByIdsBuilder:
            """
            Get the release status for multiple instances
            """
            return self.GetReleaseStatusByIdsBuilder(self, release_tree_scope)
        
        class GetInstanceScopeBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                    "applyRestrictions": False, 
                    "returnPermissions": False
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[Scope]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> Result[Scope]:
                path: str = "/v3/instances/{id}/scope"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Scope)
            
            def apply_restrictions(self) -> Self:
                self.params["applyRestrictions"] = True
                return self
            
            def return_permissions(self) -> Self:
                self.params["returnPermissions"] = True
                return self
            
        def get_scope(self, instance_id: UUID) -> GetInstanceScopeBuilder:
            """
            Get the scope for the instance by its KG-internal ID
            """
            return self.GetInstanceScopeBuilder(self, instance_id)
        
        class GetSuggestedLinksForPropertyBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID, property_name: str):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                    "property": property_name
                })
            
            def invoke(self, payload: JsonLdDocument) -> EmptyResult:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(payload, self._parent.config.default_stage)

            def invoke_in_stage(self, payload: JsonLdDocument, stage: Stage) -> EmptyResult:
                path: str = "/v3/instances/{id}/suggestedLinksForProperty"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_empty_result(result)
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def search(self, search: str) -> Self:
                self.params["search"] = search
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def source_type(self, source_type: str) -> Self:
                self.params["sourceType"] = source_type
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
            def target_type(self, target_type: str) -> Self:
                self.params["targetType"] = target_type
                return self
            
        def get_suggested_links_for_property(self, instance_id: UUID, property_name: str) -> GetSuggestedLinksForPropertyBuilder:
            """
            Returns suggestions for an instance to be linked by the given property (e.g. for the KG Editor) - and takes into account the passed payload (already chosen values, reflection on dependencies between properties - e.g. providing only parcellations for an already chosen brain atlas). Please note: This service will return released values for "additionalValue" in case a user only has minimal read rights
            """
            return self.GetSuggestedLinksForPropertyBuilder(self, instance_id, property_name)
        
        class GetSuggestedLinksForProperty1Builder(object):

            def __init__(self, parent: Communication, instance_id: UUID, property_name: str):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                    "property": property_name
                })
            
            def invoke(self) -> EmptyResult:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> EmptyResult:
                path: str = "/v3/instances/{id}/suggestedLinksForProperty"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_empty_result(result)
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def search(self, search: str) -> Self:
                self.params["search"] = search
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def source_type(self, source_type: str) -> Self:
                self.params["sourceType"] = source_type
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
            def target_type(self, target_type: str) -> Self:
                self.params["targetType"] = target_type
                return self
            
        def get_suggested_links_for_property1(self, instance_id: UUID, property_name: str) -> GetSuggestedLinksForProperty1Builder:
            """
            Returns suggestions for an instance to be linked by the given property (e.g. for the KG Editor). Please note: This service will return released values for "additionalValue" in case a user only has minimal read rights
            """
            return self.GetSuggestedLinksForProperty1Builder(self, instance_id, property_name)
        
        class InviteUserForInstanceBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID, user_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.user_id: UUID = user_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/instances/{id}/invitedUsers/{userId}"
                path = path.replace("{id}", str(self.instance_id))
                path = path.replace("{userId}", str(self.user_id))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_empty_result(result)
            
        def invite_user_for(self, instance_id: UUID, user_id: UUID) -> InviteUserForInstanceBuilder:
            """
            Create or update an invitation for the given user to review the given instance
            """
            return self.InviteUserForInstanceBuilder(self, instance_id, user_id)
        
        class ListInstancesBuilder(object):

            def __init__(self, parent: Communication, target_type: str):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                    "type": target_type
                })
            
            def invoke(self) -> ResultPage[Instance]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> ResultPage[Instance]:
                path: str = "/v3/instances"
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result_page(ResultPageBuilderContext(self, self.invoke_in_stage, stage=stage), self._parent.config.id_namespace, result, Instance)
            
            def filter_property(self, filter_property: str) -> Self:
                self.params["filterProperty"] = filter_property
                return self
            
            def filter_value(self, filter_value: str) -> Self:
                self.params["filterValue"] = filter_value
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def search_by_label(self, search_by_label: str) -> Self:
                self.params["searchByLabel"] = search_by_label
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def space(self, space: str) -> Self:
                self.params["space"] = space
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
        def list(self, target_type: str) -> ListInstancesBuilder:
            """
            Returns a list of instances according to their types
            """
            return self.ListInstancesBuilder(self, target_type)
        
        class ListInvitationsBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/instances/{id}/invitedUsers"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_empty_result(result)
            
        def list_invitations(self, instance_id: UUID) -> ListInvitationsBuilder:
            """
            List invitations for review for the given instance
            """
            return self.ListInvitationsBuilder(self, instance_id)
        
        class ListInstancesWithInvitationsBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[ListOfUUID]:
                path: str = "/v3/instancesWithInvitations"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, ListOfUUID)
            
        def list_with_invitations(self, ) -> ListInstancesWithInvitationsBuilder:
            """
            List instances with invitations
            """
            return self.ListInstancesWithInvitationsBuilder(self)
        
        class MoveInstanceBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID, space: str):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.space: str = space
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[Instance]:
                path: str = "/v3/instances/{id}/spaces/{space}"
                path = path.replace("{id}", str(self.instance_id))
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
            def incoming_links_page_size(self, incoming_links_page_size: int) -> Self:
                self.params["incomingLinksPageSize"] = incoming_links_page_size
                return self
            
            def return_alternatives(self, return_alternatives: bool) -> Self:
                self.params["returnAlternatives"] = return_alternatives
                return self
            
            def return_embedded(self, return_embedded: bool) -> Self:
                self.params["returnEmbedded"] = return_embedded
                return self
            
            def return_incoming_links(self, return_incoming_links: bool) -> Self:
                self.params["returnIncomingLinks"] = return_incoming_links
                return self
            
            def return_payload(self, return_payload: bool) -> Self:
                self.params["returnPayload"] = return_payload
                return self
            
            def return_permissions(self, return_permissions: bool) -> Self:
                self.params["returnPermissions"] = return_permissions
                return self
            
        def move(self, instance_id: UUID, space: str) -> MoveInstanceBuilder:
            """
            Move an instance to another space
            """
            return self.MoveInstanceBuilder(self, instance_id, space)
        
        class ReleaseInstanceBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/instances/{id}/release"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, None, invocation_params)
                return translate_empty_result(result)
            
            def revision(self, revision: str) -> Self:
                self.params["revision"] = revision
                return self
            
        def release(self, instance_id: UUID) -> ReleaseInstanceBuilder:
            """
            Release or re-release an instance
            """
            return self.ReleaseInstanceBuilder(self, instance_id)
        
        class RevokeUserInvitationBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID, user_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.user_id: UUID = user_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/instances/{id}/invitedUsers/{userId}"
                path = path.replace("{id}", str(self.instance_id))
                path = path.replace("{userId}", str(self.user_id))
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
        def revoke_user_invitation(self, instance_id: UUID, user_id: UUID) -> RevokeUserInvitationBuilder:
            """
            Revoke an invitation for the given user to review the given instance
            """
            return self.RevokeUserInvitationBuilder(self, instance_id, user_id)
        
        class UnreleaseInstanceBuilder(object):

            def __init__(self, parent: Communication, instance_id: UUID):
                self._parent = parent
                
                self.instance_id: UUID = instance_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/instances/{id}/release"
                path = path.replace("{id}", str(self.instance_id))
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
        def unrelease(self, instance_id: UUID) -> UnreleaseInstanceBuilder:
            """
            Unrelease an instance
            """
            return self.UnreleaseInstanceBuilder(self, instance_id)
        
    class Jsonld(Communication):
        def __init__(self, config: Config):
            super().__init__(config)
    
        class NormalizePayloadBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self, payload: JsonLdDocument) -> EmptyResult:
                path: str = "/v3/jsonld/normalizedPayload"
                invocation_params = self.params
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_empty_result(result)
            
        def normalize_payload(self, ) -> NormalizePayloadBuilder:
            """
            Normalizes the passed payload according to the EBRAINS KG conventions
            """
            return self.NormalizePayloadBuilder(self)
        
    class Queries(Communication):
        def __init__(self, config: Config):
            super().__init__(config)
    
        class ExecuteQueryByIdBuilder(object):

            def __init__(self, parent: Communication, query_id: UUID):
                self._parent = parent
                
                self.query_id: UUID = query_id
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                })
            
            def invoke(self) -> ResultPage[JsonLdDocument]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> ResultPage[JsonLdDocument]:
                path: str = "/v3/queries/{queryId}/instances"
                path = path.replace("{queryId}", str(self.query_id))
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result_page(ResultPageBuilderContext(self, self.invoke_in_stage, stage=stage), self._parent.config.id_namespace, result, JsonLdDocument)
            
            def additional_parameter(self, key: str, value: Any):
                if key in ["instanceId", "queryId", "restrictToSpaces", "returnTotalResults", "size", "stage", "from"]:
                    raise ValueError(f"You've tried to set the value for {key} via the 'additional_parameter' method although this is a strict parameter already. Please use the respective method.")
                self.params[key] = value
                return self
                
            def instance_id(self, instance_id: UUID) -> Self:
                self.params["instanceId"] = instance_id
                return self
            
            def restrict_to_spaces(self, restrict_to_spaces: List[str]) -> Self:
                self.params["restrictToSpaces"] = restrict_to_spaces
                return self
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
        def execute_query_by_id(self, query_id: UUID) -> ExecuteQueryByIdBuilder:
            """
            Execute a stored query to receive the instances
            """
            return self.ExecuteQueryByIdBuilder(self, query_id)
        
        class GetQuerySpecificationBuilder(object):

            def __init__(self, parent: Communication, query_id: UUID):
                self._parent = parent
                
                self.query_id: UUID = query_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[Instance]:
                path: str = "/v3/queries/{queryId}"
                path = path.replace("{queryId}", str(self.query_id))
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
        def get_query_specification(self, query_id: UUID) -> GetQuerySpecificationBuilder:
            """
            Get the query specification with the given query id in a specific space
            """
            return self.GetQuerySpecificationBuilder(self, query_id)
        
        class ListQueriesPerRootTypeBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                })
            
            def invoke(self) -> ResultPage[Instance]:
                path: str = "/v3/queries"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result_page(ResultPageBuilderContext(self, self.invoke), self._parent.config.id_namespace, result, Instance)
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def search(self, search: str) -> Self:
                self.params["search"] = search
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
            def target_type(self, target_type: str) -> Self:
                self.params["type"] = target_type
                return self
            
        def list_per_root_type(self, ) -> ListQueriesPerRootTypeBuilder:
            """
            List the queries and filter them by root type and/or text in the label, name or description
            """
            return self.ListQueriesPerRootTypeBuilder(self)
        
        class RemoveQueryBuilder(object):

            def __init__(self, parent: Communication, query_id: UUID):
                self._parent = parent
                
                self.query_id: UUID = query_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> EmptyResult:
                path: str = "/v3/queries/{queryId}"
                path = path.replace("{queryId}", str(self.query_id))
                invocation_params = self.params
                result: Response = self._parent.delete_request(path, invocation_params)
                return translate_empty_result(result)
            
        def remove_query(self, query_id: UUID) -> RemoveQueryBuilder:
            """
            Remove a query specification
            """
            return self.RemoveQueryBuilder(self, query_id)
        
        class RunDynamicQueryBuilder(object):

            def __init__(self, parent: Communication, ):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                })
            
            def invoke(self, payload: JsonLdDocument) -> ResultPage[JsonLdDocument]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(payload, self._parent.config.default_stage)

            def invoke_in_stage(self, payload: JsonLdDocument, stage: Stage) -> ResultPage[JsonLdDocument]:
                path: str = "/v3/queries"
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_result_page(ResultPageBuilderContext(self, self.invoke_in_stage, payload=payload, stage=stage), self._parent.config.id_namespace, result, JsonLdDocument)
            
            def additional_parameter(self, key: str, value: Any):
                if key in ["instanceId", "restrictToSpaces", "returnTotalResults", "size", "stage", "from"]:
                    raise ValueError(f"You've tried to set the value for {key} via the 'additional_parameter' method although this is a strict parameter already. Please use the respective method.")
                self.params[key] = value
                return self
                
            def instance_id(self, instance_id: UUID) -> Self:
                self.params["instanceId"] = instance_id
                return self
            
            def restrict_to_spaces(self, restrict_to_spaces: List[str]) -> Self:
                self.params["restrictToSpaces"] = restrict_to_spaces
                return self
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
        def run_dynamic_query(self, ) -> RunDynamicQueryBuilder:
            """
            Execute the query in the payload (e.g. for execution before saving with the KG QueryBuilder)
            """
            return self.RunDynamicQueryBuilder(self)
        
        class SaveQueryBuilder(object):

            def __init__(self, parent: Communication, query_id: UUID):
                self._parent = parent
                
                self.query_id: UUID = query_id
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self, payload: JsonLdDocument) -> Result[Instance]:
                path: str = "/v3/queries/{queryId}"
                path = path.replace("{queryId}", str(self.query_id))
                invocation_params = self.params
                result: Response = self._parent.put_request(path, payload, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, Instance)
            
            def space(self, space: str) -> Self:
                self.params["space"] = space
                return self
            
        def save_query(self, query_id: UUID) -> SaveQueryBuilder:
            """
            Create or save a query specification
            """
            return self.SaveQueryBuilder(self, query_id)
        
    class Setup(Communication):
        def __init__(self, config: Config):
            super().__init__(config)
    
        class GetOpenIdConfigUrlBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[JsonLdDocument]:
                path: str = "/v3/setup/authentication"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, JsonLdDocument)
            
        def get_open_id_config_url(self, ) -> GetOpenIdConfigUrlBuilder:
            """
            Get the endpoint of the configured openid configuration
            """
            return self.GetOpenIdConfigUrlBuilder(self)
        
    class Spaces(Communication):
        def __init__(self, config: Config):
            super().__init__(config)
    
        class GetSpaceBuilder(object):

            def __init__(self, parent: Communication, space: str):
                self._parent = parent
                
                self.space: str = space
                self.params: Dict[str, Any] = {
                    "permissions": False
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[SpaceInformation]:
                path: str = "/v3/spaces/{space}"
                path = path.replace("{space}", str(self.space))
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, SpaceInformation)
            
            def permissions(self) -> Self:
                self.params["permissions"] = True
                return self
            
        def get(self, space: str) -> GetSpaceBuilder:
            
            return self.GetSpaceBuilder(self, space)
        
        class ListSpacesBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                    "permissions": False, 
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0
                }
                self.params.update({
                })
            
            def invoke(self) -> ResultPage[SpaceInformation]:
                path: str = "/v3/spaces"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result_page(ResultPageBuilderContext(self, self.invoke), self._parent.config.id_namespace, result, SpaceInformation)
            
            def permissions(self) -> Self:
                self.params["permissions"] = True
                return self
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
        def list(self, ) -> ListSpacesBuilder:
            
            return self.ListSpacesBuilder(self)
        
    class Types(Communication):
        def __init__(self, config: Config):
            super().__init__(config)
    
        class GetTypesByNameBuilder(object):

            def __init__(self, parent: Communication, ):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                    "withIncomingLinks": False, 
                    "withProperties": False
                }
                self.params.update({
                })
            
            def invoke(self, payload: List[str]) -> ResultsById[TypeInformation]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(payload, self._parent.config.default_stage)

            def invoke_in_stage(self, payload: List[str], stage: Stage) -> ResultsById[TypeInformation]:
                path: str = "/v3/typesByName"
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.post_request(path, payload, invocation_params)
                return translate_results_by_id(self._parent.config.id_namespace, result, TypeInformation)
            
            def space(self, space: str) -> Self:
                self.params["space"] = space
                return self
            
            def with_incoming_links(self) -> Self:
                self.params["withIncomingLinks"] = True
                return self
            
            def with_properties(self) -> Self:
                self.params["withProperties"] = True
                return self
            
        def get_by_name(self, ) -> GetTypesByNameBuilder:
            """
            Returns the types according to the list of names - either with property information or without
            """
            return self.GetTypesByNameBuilder(self)
        
        class ListTypesBuilder(object):

            def __init__(self, parent: Communication, ):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                    "returnTotalResults": True, 
                    "size": 50, 
                    "from": 0, 
                    "withIncomingLinks": False, 
                    "withProperties": False
                }
                self.params.update({
                })
            
            def invoke(self) -> ResultPage[TypeInformation]:
                """
                Invokes the query for the default stage as configured for the overall client
                """
                return self.invoke_in_stage(self._parent.config.default_stage)

            def invoke_in_stage(self, stage: Stage) -> ResultPage[TypeInformation]:
                path: str = "/v3/types"
                invocation_params = copy.deepcopy(self.params)
                invocation_params["stage"] = stage
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result_page(ResultPageBuilderContext(self, self.invoke_in_stage, stage=stage), self._parent.config.id_namespace, result, TypeInformation)
            
            def return_total_results(self, return_total_results: bool) -> Self:
                self.params["returnTotalResults"] = return_total_results
                return self
            
            def size(self, size: int) -> Self:
                self.params["size"] = size
                return self
            
            def space(self, space: str) -> Self:
                self.params["space"] = space
                return self
            
            def start(self, start: int) -> Self:
                self.params["from"] = start
                return self
            
            def with_incoming_links(self) -> Self:
                self.params["withIncomingLinks"] = True
                return self
            
            def with_properties(self) -> Self:
                self.params["withProperties"] = True
                return self
            
        def list(self, ) -> ListTypesBuilder:
            """
            Returns the types available - either with property information or without
            """
            return self.ListTypesBuilder(self)
        
    class Users(Communication):
        def __init__(self, config: Config):
            super().__init__(config)
    
        class MyUserInfoBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[User]:
                path: str = "/v3/users/me"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, User)
            
        def my_info(self, ) -> MyUserInfoBuilder:
            """
            Retrieve user information from the passed token (including detailed information such as e-mail address)
            """
            return self.MyUserInfoBuilder(self)
        
        class MyRolesBuilder(object):

            def __init__(self, parent: Communication):
                self._parent = parent
                
                self.params: Dict[str, Any] = {
                }
                self.params.update({
                })
            
            def invoke(self) -> Result[UserWithRoles]:
                path: str = "/v3/users/me/roles"
                invocation_params = self.params
                result: Response = self._parent.get_request(path, invocation_params)
                return translate_result(self._parent.config.id_namespace, result, UserWithRoles)
            
        def my_roles(self, ) -> MyRolesBuilder:
            """
            Retrieve the roles for the current user
            """
            return self.MyRolesBuilder(self)
        
    class ClientBuilder(AbstractClientBuilder):

        def __init__(self, host_name: str, config: dict[str, any]):
            super().__init__(host_name, config.get("idNamespace"), config.get("loginClientId", None), fetch_by_open_id_config(config.get("endpoint", None)))

        def build(self, default_stage: Stage):
            return MarmotGraph.Client(self._create_config(default_stage))

    @staticmethod
    def client(host_name: str, tenant:str = "default"):
        config = {}
        global_config = requests.get(create_endpoint(host_name, "/v3/setup/authentication"))
        if global_config and global_config.status_code == 200:
            config.update(global_config.json().get("data", {}))
            tenant_config = requests.get(create_endpoint(host_name, f"/v3/tenants/{tenant}"))
            if tenant_config and tenant_config.status_code == 200:
                tenant_config = tenant_config.json()
                config.update(tenant_config)
                return MarmotGraph.ClientBuilder(host_name, config)
            else:
                raise ValueError(
                    f"Was not able to read configuration of MarmotGraph tenant {tenant} on endpoint {host_name}")
            pass
        else:
            raise ValueError(f"Was not able to read configuration of MarmotGraph endpoint at {host_name}")

def _fetch_oidc_config(marmot_host_name: str) -> Optional[OIDCConfig]:
    unauthenticated_client = MarmotGraph.Client(
        Config(marmot_host_name, None, None,
               None, False, Stage.RELEASED)
    )
    response: Result[JsonLdDocument] = unauthenticated_client.setup.get_open_id_config_url().invoke()
    if response and response.is_successful() and "endpoint" in response.instance:
        return fetch_by_open_id_config(response.instance["endpoint"])
    return None
